
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lkp-nfs
spec:
  storageClassName: "nfs-csi"
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 10.73.1.10 # ip of nfs server
    path: "/srv/nfs" # path to directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lkp-nfs
spec:
  storageClassName: "nfs-csi"
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
